name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:
    - uses: actions/checkout@master
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Build release binary
      run: cargo build --release
    
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        make_latest: 'true'
        files: |
          ./target/release/eas-env