name: Release
permissions:
  contents: write
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Rustup add target x86_64-apple-darwin
      run: rustup target add x86_64-apple-darwin
    - name: Build release binary
      run: cargo build --release --target x86_64-apple-darwin
    
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        make_latest: 'true'
        files: |
          ./target/release/eas-env